import { Archivo, Figtree } from "next/font/google";
import "./globals.css";

export const archivo = Archivo({
  subsets: ["latin"],
  variable: "--font-archivo",
});

export const figtree = Figtree({
  subsets: ["latin"],
  variable: "--font-figtree",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${archivo.variable} ${figtree.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
